apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - sources.yaml
  - kube-prometheus-stack-helmrelease.yaml
  - loki-helmrelease.yaml
  - grafana-ingress.yaml
  - loki-ingress.yaml
  - prometheus-ingress.yaml
  - pushgateway/
  - ntfy/
