apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-tls
  namespace: vaultwarden
spec:
  secretName: vaultwarden-tls
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - vaultwarden.home.t12.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - vaultwarden.home.t12.io
      secretName: vaultwarden-tls
  rules:
    - host: vaultwarden.home.t12.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaultwarden
                port:
                  number: 80
