apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: dns
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:2024.07.0
          env:
            - name: TZ
              value: "Europe/Dublin"
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: password
            - name: PIHOLE_DNS_
              value: "1.1.1.1;1.0.0.1"
            - name: DNSSEC
              value: "false"
          ports:
            - containerPort: 53
              protocol: UDP
              name: dns-udp
            - containerPort: 53
              protocol: TCP
              name: dns-tcp
            - containerPort: 80
              protocol: TCP
              name: web
          volumeMounts:
            - name: data
              mountPath: /etc/pihole
            - name: custom-dns
              mountPath: /etc/dnsmasq.d/99-home.conf
              subPath: home.t12.io.conf
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /admin
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pihole-data
        - name: custom-dns
          configMap:
            name: pihole-custom-dns
