apiVersion: ENC[AES256_GCM,data:Rno=,iv:XzlvwICGQIxdcmxp/S4d8ppXF6DYq5BhRRUH3CIiD+M=,tag:iIS3ZwhyEeLnKh1wQ8oRXg==,type:str]
kind: ENC[AES256_GCM,data:GJmmm0pg,iv:rlEohAPV/GwjLf6vKOli2bLJSUX8ZoSK1GpO8Xbpit4=,tag:JaETIhaYvCELfriBNJn9dw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GD99F3hI48TCgQUpeA==,iv:YulorIXvrYAlWdr/W+JLZxQgbLTVPdhSDwXVW+h7EqE=,tag:ZKMOwtsq5J2krbl2ZXngPw==,type:str]
    namespace: ENC[AES256_GCM,data:vkYP,iv:nZUrmLdxcwCkBOJ4oIRdlHPLTaIsRnncKce0SiorupM=,tag:XV6D/Mk2PkVjm4bamyU2rg==,type:str]
type: ENC[AES256_GCM,data:OBfpPcT3,iv:Ae07pnmENIvyIwX7LIuWYegGNcBjstufqq+ug9I/lq0=,tag:jneEW0mAdQ7AJeTN2xjqhA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:YCoHGazufU26,iv:+YLwvUfPPpSacf2luOFb9eYD/y/UjtO5tti6NS8RmJc=,tag:wIMnL5jnZPr8Eqa94zbLmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hd3e8af00v68rkjv87fqk8k8q98rd6zc4tujvtenuc2fx329my3s8dktug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRStib2tMSjVoR1l6ajJM
            SkxIVm1GREZzajVSMEJZdEY1TUUzYWljZFhnCk9tcE0zcThhaTJsMzFvSzBkaDdX
            VVlWQitWUkFWNmZPMFFlR1YwWFdwRkUKLS0tIGlob3UzUTE0WlVpRGhJbXV2Y0R0
            aGd4RzNUTVhuYlNYU3ZlbVVTNm9MOXcKFgwhSsPA/gJ2Yfdr6GHmYTOGZwo+S3Vj
            CYLc1iuFs17RK0y62dxW4jfsgTupmr5GGp1MqZOVftczyw9UphMFJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T09:44:17Z"
    mac: ENC[AES256_GCM,data:vDAnGdznqQEKWql7v9nq2OPntgWV+2aFzkFuzO9Q0mnYIrAB/ApC1tvR3FzZnwPbWb0SAODF3yqcvNF6w5Ia/ccTDyp3cBuzPh2UINMtjrN/1LpXcZ+Xkqi8TzfXiZ+wdJfAJzC/2EB09ZRVpjf2/XAMy+p86wgzh97DO/SUKP4=,iv:skU/f6Y8KCCJgdtHl5Sye7TUmJ9jlD2K8ahtOBs+hiw=,tag:1lv6e9qgWAzUOmqDRNhFKA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
