apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - vault-cache-pvc.yaml
  - vault-data-pvc.yaml
  - configmap.yaml
  - cronjob.yaml
  - consumer-deployment.yaml
