apiVersion: v1
kind: PersistentVolume
metadata:
  name: obsidian-vault-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.123
    path: /home/pybash/Documents/obsidian-vault
    readOnly: true
