apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-vault
  namespace: vault-ingest
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: obsidian-vault-nfs
  storageClassName: ""
