apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
  namespace: vault-ingest
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 500Mi
