apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ntfy-tls
  namespace: monitoring
spec:
  secretName: ntfy-tls
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - ntfy.home.t12.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntfy
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ntfy.home.t12.io
      secretName: ntfy-tls
  rules:
    - host: ntfy.home.t12.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ntfy
                port:
                  number: 80
