apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: nextcloud
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:cSMW0k50Gmqd,iv:0b/hvw7o11T6m35EPdRE6Sf/SLkfbvH0xoa6HpNtLns=,tag:NtkIh1vhqQvCO6a6ekdTTw==,type:str]
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:WyI4BYVj,iv:TyMlCoRB3KzACIDjPepNS9n5orYaCYy97N81PfLjTPk=,tag:CkLknjXlFReNrEF5gPacLg==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:PlPbHqce3TdY,iv:NEZtuE0snuv5NBRBvyTdmuhvpX8nTuVpfn0Yh9Dk0Pg=,tag:KVrtm8caNrOJOz5VgK4+4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hd3e8af00v68rkjv87fqk8k8q98rd6zc4tujvtenuc2fx329my3s8dktug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNWVPQ2hMZElyZm9hK1N4
            WkpjejJLZ3AxalJNSUtsVTRsaHJkQ2l5SkRFCmtFYkMxeUJJYmUwNytrSDR5TjNk
            cjdhQXRBS29DbjRIMEhCKzdPUjZ5SU0KLS0tIHg1alA1dGx4L0VrYmV4QzFVMGh3
            WDhBeWpXY3B4enc1ZGFyK0xyWDArejgKgtW069L6hg0WOOEaJp3qDJ6dt/4J66Ua
            VpTWH7oSs2qyufmXBDQjsSI75AR1fVyExk8pk6EcKc8BetjqrAKvoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T09:37:45Z"
    mac: ENC[AES256_GCM,data:TbbNBPv/4j0OO10XpX3J6TgiN0jSnGhSS/XTsNoU9EdOZpEyvamlCoK4TFm+MY/AIqpJQ0Npf8WcL2tD6rNNp6Twhe9zdDILamsjBiRiSwxZWTzFnMYCg4Yk5S6JJqrlj1dCKgmn6y/7e1mt3hLc3MEHj/dWda8fex/SNdNd2qU=,iv:kNE8V7bAkwJ/DMu+5wEE1GZYaBaW5ModY0SLYvHIkHo=,tag:JNwxgrrqjvjzE0vgiDAQWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
