all:
  children:
    control_plane:
      hosts:
        cp1:
          ansible_host: 192.168.1.101
        cp2:
          ansible_host: 192.168.1.102
        cp3:
          ansible_host: 192.168.1.103
      vars:
        ansible_user: sre
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519

    workers:
      hosts:
        wk1:
          ansible_host: 192.168.1.111
          ansible_user: sre
        wk2:
          ansible_host: 192.168.1.112
          ansible_user: sre
        wk3:
          ansible_host: 192.168.1.113
          ansible_user: sre
      vars:
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
