apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny-ingress.yaml
  - allow-from-ingress-nginx.yaml
  - allow-from-kube-system.yaml
  - allow-intra-namespace.yaml
