apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-platform
resources:
  - namespace.yaml
  - sources.yaml
  - litellm-secret.sops.yaml
  - litellm-helmrelease.yaml
  - open-webui-helmrelease.yaml
  - qdrant-helmrelease.yaml
