apiVersion: ENC[AES256_GCM,data:xsA=,iv:PmJkSVNqvWO/IgYiTmC5aM9XI+4mQOI7t36D7gD4jHg=,tag:KybvoxhXBP39+3W/+lpyEA==,type:str]
kind: ENC[AES256_GCM,data:iWd7w/2v,iv:llhPfTmWSTYPqaMrJ1MfXnYmcbSm+H+bmmr8Hs/LBLk=,tag:ul4nz+TScglfxirwWkqlgg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uLbTFlTm3aUyu2TWLh9p,iv:+dsZiRrtlEtlg+YjMRdMjgR8i4GzHWVcZu7EwbmdGpU=,tag:r0KPCESChjNeD/iDytFQmg==,type:str]
    namespace: ENC[AES256_GCM,data:0uDkyHGqn5OfKl0=,iv:Koh91NpEJ9PW2qC6gBzNxO82Z+HEeGDerlOSAGsPzGU=,tag:U09QzxhVZddVkc5Q12gouA==,type:str]
type: ENC[AES256_GCM,data:udAsEV34,iv:YcDrpIuziguog/GRVqivEMQRb4Lz/Fdo7YE+ZybOFwo=,tag:3etifP2toKE2vTxAMN8Uog==,type:str]
stringData:
    master-key: ENC[AES256_GCM,data:4TfjbGJqLogFkVBGALwUvLR1boqzTg==,iv:jfFbvkn/1fTkceLEEwdmPR/y3EhGnkFEsxrULu+S0dQ=,tag:z3KD2KQpz7U+IW444YSK+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hd3e8af00v68rkjv87fqk8k8q98rd6zc4tujvtenuc2fx329my3s8dktug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeTFrSkg3MkVvUnI3cGRa
            NWJidE9FeTJqOGZFb252SFR0Um04alBwa2hNCkN5L1lFZDB6c3Y2TklWTStnOHYv
            cjBoUTMxZVlVQTBaMGw4UFppbkMvWE0KLS0tIEFsT3VDdzB5WllaOFhIUStTZlFM
            c0QzTzdJU3dzUmJIRE9DdXVROWFER28K6n4z0MWsPItkhGrGCG4EZdrTSMRcHSz1
            Ev/lDfcuYjFUKJTsuGr9fVpBW7JUrrhwaPHfNUd0pWW7CPH8Q3lOQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T18:33:17Z"
    mac: ENC[AES256_GCM,data:i4Nem22DqsFnqV81LgAY+dWfXPbVrVy71WNIPHnat3XAPdjcPqkDY5nKEpWPFaV6o5JYwVh4IuQwdYzzqs4NzHaca2Fuyxm4VpGphhrCNY+HoF5aPU7nTXx53SsPo9xoD5mFDTZs339TvR3mNGQzMxKAKLEdLvk+MmzL380T4QQ=,iv:ahIhm5rHNVo8MMtIIENnxHPoBVD4YFOdAX7IQ9qnydA=,tag:Ej4iBvm004jKv2v51niWSA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
