---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: homelab-gitops
  namespace: ai-platform
spec:
  interval: 1m
  url: ssh://git@gitlab.com/pybashinf-group/homelab-gitops.git
  ref:
    branch: main
  secretRef:
    name: flux-system
    namespace: flux-system
